### ISSUE TITLE
Not getting smaller

### ISSUE THREAD

**Issue by SeizoYT** [Tehiii/Minipeople#2]
Hello Tehiii,

i just downloaded your mod and loaded minecraft, when i looked at the other players they were not smaller, but bigger , is this a glitch because my armor is small and i am big, if you could help that would be appriciated,

Thanks, SeizoYT

**Comment by Tehiii** [comment]
It was april fools update, you can now download the normal version from here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2421484
