### ISSUE TITLE
Hat layer doesn't work in skins + Some mobs don't make smaller

### ISSUE THREAD

**Issue by ArceCreeper** [Tehiii/Minipeople#3]
I tried the mod in 1.9, and I found that the Hat layer in skins doesn't work in players (it works in skulls) and some mobs don't shrink.

![](http://i.imgur.com/FFDg5LP.png)

![](http://i.imgur.com/U3NDCKV.png)

**Comment by Tehiii** [comment]
All mobs arent tiny yet, and hat layer will be fixed in next update, and it will come soon.
